### Site Settings ###
title               : Vishal Gattani
description         : >-                               # >- means to ignore newlines until "url:"
                      "I use tabs over spaces."

url                 : ""                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : ""                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : YoussefRaafatNasry/portfolYOU    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
#remote_theme       : YoussefRaafatNasry/portfolYOU    # uncomment this if you are using it as a remote theme


### Build Settings ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                        # Pages with the following paths will be excluded from navbar
  - 404.html
  - index.html
  - blog/tags.html
  - blog/page-:num/index.html


### Author Info ###
author:
  name              : Vishal Gattani
  image             : "/images/southpark.jpg?raw=true"
# behance           : your_username
# dribbble          : your_username
  email             : vgattani@umd.edu
# facebook          : your_username
  github            : vishalgattani
# gitlab            : your_username
  instagram         : vishalgattani
  linkedin          : VishalGattani
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
paginate: 6
paginate_path: "/blog/page-:num/"


### Posts Permalink ###
permalink: blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
